### PR TITLE
Fix Project and update tests

### PR DESCRIPTION
**Pull request by networkfusion**
## Motivation and Context
* The project file was missing `<Content Include="packages.lock.json" />`
* Fixes deprecated functions in unit tests.
* Fixes test namespace

## Types of changes

- [ ] Improvement (non-breaking change that improves a feature, code or algorithm)
- [x] Bug fix (non-breaking change which fixes an issue with code or algorithm)
- [ ] New feature (non-breaking change which adds functionality to code)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)
- [ ] Config and build (change in the configuration and build system, has no impact on code or features)
- [ ] Dependencies (update dependencies and changes associated, has no impact on code or features)
- [x] Unit Tests (add new Unit Test(s) or improved existing one(s), has no impact on code or features)
- [ ] Documentation (changes or updates in the documentation, has no impact on code or features)

## Checklist:

- [ ] My code follows the code style of this project (only if there are changes in source code).
- [ ] My changes require an update to the documentation (there are changes that require the docs website to be updated).
- [ ] I have updated the documentation accordingly (the changes require an update on the docs in this repo).
- [ ] I have read the [CONTRIBUTING](https://github.com/nanoframework/.github/blob/master/CONTRIBUTING.md) document.
- [ ] I have tested everything locally and all new and existing tests passed (only if there are changes in source code).
- [ ] I have added new tests to cover my changes.

### CODE REVIEW

**Review by Ellerbach — APPROVED** [review]
Seems good to me! Thanks for the work!
I guess they are still green when you run them locally? :-)

**Comment by networkfusion** [comment]
> Seems good to me! Thanks for the work! I guess they are still green when you run them locally? :-)

Yes, with no deprecation warnings :-)

image

**Comment by networkfusion** [comment]
@josesimoes , this one still seems to be hitting rate limits, but as far as I can see there is no reason.

No rush though as this should still work against the deprecated functions (although addition of the packages.lock.json might have an effect on the docs repo once it builds that far).

**Comment by josesimoes** [comment]
Nothing I can spot either. I would say that it had the bad timming of running on a hour that had indeed hit the rate limit.

**Pull request merged**
